[package]
name = "nyquest-backend-cronet"
description = "Cronet backend for nyquest"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
exclude.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
async = ["nyquest-interface/async", "dep:futures-util"]
async-stream = ["async", "nyquest-interface/async-stream"]
blocking = ["nyquest-interface/blocking"]
blocking-stream = ["blocking", "nyquest-interface/blocking-stream"]

[dependencies]
nyquest-interface = { version = "0.4.0", path = "../../nyquest-interface", default-features = false }
url = "2"
futures-util = { version = "0.3", optional = true, default-features = false, features = ["io"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"

